apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080       # ← access via http://localhost:30080 from your laptop
  selector:
    app: tomcat