-- MySQL Script generated by MySQL Workbench
-- Wed Nov 26 12:38:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lms` DEFAULT CHARACTER SET utf8 ;
USE `lms` ;

-- -----------------------------------------------------
-- Table `lms`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Role` (
  `RoleID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` ENUM('guest', 'registered_user', 'librarian', 'administrator') NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  UNIQUE INDEX (`Name` ASC) VISIBLE,
  PRIMARY KEY (`RoleID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Genre` (
  `GenreID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  UNIQUE INDEX (`Name` ASC) VISIBLE,
  PRIMARY KEY (`GenreID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Author` (
  `AuthorID` BIGINT NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Biography` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `uk_full_name` (`FirstName` ASC, `LastName` ASC) VISIBLE,
  INDEX `idx_last_name` (`LastName` ASC) VISIBLE,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`BookStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`BookStatus` (
  `BookStatusID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  UNIQUE INDEX (`Name` ASC) VISIBLE,
  PRIMARY KEY (`BookStatusID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`ActionCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`ActionCategory` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CategoryID`),
  UNIQUE INDEX `Category_UNIQUE` (`Category` ASC) VISIBLE,
  UNIQUE INDEX `CategoryID_UNIQUE` (`CategoryID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`AuditLogAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`AuditLogAction` (
  `AuditActionID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Action` VARCHAR(100) NOT NULL,
  `CategoryID` INT NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  UNIQUE INDEX (`Action` ASC) VISIBLE,
  PRIMARY KEY (`AuditActionID`),
  INDEX `fk_auditlog_actions_cat_idx` (`CategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_auditlog_actions_cat`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `lms`.`ActionCategory` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`AccountStanding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`AccountStanding` (
  `StandingID` TINYINT UNSIGNED NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  UNIQUE INDEX (`Name` ASC) VISIBLE,
  PRIMARY KEY (`StandingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`UserAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`UserAccount` (
  `UserID` BIGINT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(20) NULL DEFAULT NULL,
  `Address` TEXT NULL DEFAULT NULL,
  `RoleID` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  `AccountStanding` TINYINT UNSIGNED NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LastLoginAt` TIMESTAMP NULL DEFAULT NULL,
  `LastReminderSentAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX (`Email` ASC) VISIBLE,
  PRIMARY KEY (`UserID`),
  INDEX `idx_email` (`Email` ASC) VISIBLE,
  INDEX `idx_role` (`RoleID` ASC) VISIBLE,
  INDEX `fk_users_standing_idx` (`AccountStanding` ASC) VISIBLE,
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`RoleID`)
    REFERENCES `lms`.`Role` (`RoleID`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_users_standing`
    FOREIGN KEY (`AccountStanding`)
    REFERENCES `lms`.`AccountStanding` (`StandingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Book` (
  `BookID` BIGINT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(13) NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `AuthorID` BIGINT NOT NULL,
  `GenreID` INT NOT NULL,
  `Publisher` VARCHAR(255) NULL DEFAULT NULL,
  `PublicationYear` YEAR NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CreatedBy` BIGINT NULL DEFAULT NULL,
  `UpdatedBy` BIGINT NULL DEFAULT NULL,
  UNIQUE INDEX (`ISBN` ASC) VISIBLE,
  PRIMARY KEY (`BookID`),
  FULLTEXT INDEX `ft_search` (`Title`, `ISBN`) VISIBLE,
  INDEX `idx_genre` (`GenreID` ASC) VISIBLE,
  INDEX `idx_title` (`Title` ASC) VISIBLE,
  INDEX `fk_books_created_by` (`CreatedBy` ASC) VISIBLE,
  INDEX `fk_books_updated_by` (`UpdatedBy` ASC) VISIBLE,
  INDEX `fk_books_authorid_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `fk_books_genre`
    FOREIGN KEY (`GenreID`)
    REFERENCES `lms`.`Genre` (`GenreID`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_books_created_by`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_books_updated_by`
    FOREIGN KEY (`UpdatedBy`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_books_authorid`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `lms`.`Author` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`BookCopy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`BookCopy` (
  `BookCopyID` BIGINT NOT NULL AUTO_INCREMENT,
  `BookID` BIGINT NOT NULL,
  `StatusID` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `Location` VARCHAR(50) NULL DEFAULT NULL,
  `AcquisitionDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`BookCopyID`),
  INDEX `idx_book` (`BookID` ASC) VISIBLE,
  INDEX `idx_status` (`StatusID` ASC) VISIBLE,
  CONSTRAINT `fk_instance_book`
    FOREIGN KEY (`BookID`)
    REFERENCES `lms`.`Book` (`BookID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_instance_status`
    FOREIGN KEY (`StatusID`)
    REFERENCES `lms`.`BookStatus` (`BookStatusID`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`Checkout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Checkout` (
  `CheckoutID` BIGINT NOT NULL AUTO_INCREMENT,
  `LoanedTo` BIGINT NOT NULL,
  `BookCopyID` BIGINT NOT NULL,
  `CheckoutDate` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `DueDate` DATE NOT NULL,
  `ReturnDate` DATE NULL DEFAULT NULL,
  `CheckedOutBy` BIGINT NOT NULL,
  `ReturnedBy` BIGINT NULL,
  `LateFeeAssessed` DECIMAL(6,2) UNSIGNED NULL DEFAULT 0.00,
  `LateFeePaid` TINYINT UNSIGNED NULL DEFAULT 0,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CheckoutID`),
  INDEX `idx_user` (`LoanedTo` ASC) VISIBLE,
  INDEX `idx_instance` (`BookCopyID` ASC) VISIBLE,
  INDEX `idx_due_date` (`DueDate` ASC) VISIBLE,
  INDEX `idx_return_date` (`ReturnDate` ASC) VISIBLE,
  INDEX `fk_checkout_by` (`CheckedOutBy` ASC) VISIBLE,
  INDEX `fk_returned_by` (`ReturnedBy` ASC) VISIBLE,
  CONSTRAINT `fk_checkout_user`
    FOREIGN KEY (`LoanedTo`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_checkout_instance`
    FOREIGN KEY (`BookCopyID`)
    REFERENCES `lms`.`BookCopy` (`BookCopyID`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_checkout_by`
    FOREIGN KEY (`CheckedOutBy`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_returned_by`
    FOREIGN KEY (`ReturnedBy`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`AuditLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`AuditLog` (
  `AuditEntryID` BIGINT NOT NULL AUTO_INCREMENT,
  `UserID` BIGINT NOT NULL,
  `ActionID` SMALLINT UNSIGNED NOT NULL,
  `Details` TEXT NULL DEFAULT NULL,
  `IpAddress` VARCHAR(32) NULL DEFAULT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AuditEntryID`),
  INDEX `idx_user` (`UserID` ASC) VISIBLE,
  INDEX `idx_action` (`ActionID` ASC) VISIBLE,
  INDEX `idx_created` (`CreatedAt` ASC) VISIBLE,
  CONSTRAINT `fk_audit_user`
    FOREIGN KEY (`UserID`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_audit_action`
    FOREIGN KEY (`ActionID`)
    REFERENCES `lms`.`AuditLogAction` (`AuditActionID`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lms`.`NotificationType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`NotificationType` (
  `NoficiationTypeID` TINYINT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`NoficiationTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`Notification` (
  `NotificationID` BIGINT NOT NULL AUTO_INCREMENT,
  `UserID` BIGINT NOT NULL,
  `Message` TEXT NOT NULL,
  `NotificationTypeID` TINYINT NOT NULL,
  `SentAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`NotificationID`),
  INDEX `fk_notification_type_idx` (`NotificationTypeID` ASC) VISIBLE,
  INDEX `fk_notification_userid_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_notification_type`
    FOREIGN KEY (`NotificationTypeID`)
    REFERENCES `lms`.`NotificationType` (`NoficiationTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_userid`
    FOREIGN KEY (`UserID`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`WaitlistStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`WaitlistStatus` (
  `WaitlistStatusID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`WaitlistStatusID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lms`.`WaitList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lms`.`WaitList` (
  `WaitListID` BIGINT NOT NULL,
  `BookID` BIGINT NOT NULL,
  `UserID` BIGINT NOT NULL,
  `RequestedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `StatusID` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`WaitListID`),
  INDEX `fk_waitlist_bookid_idx` (`BookID` ASC) VISIBLE,
  INDEX `fk_waitlist_userid_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_waitlist_status_idx` (`StatusID` ASC) VISIBLE,
  CONSTRAINT `fk_waitlist_bookid`
    FOREIGN KEY (`BookID`)
    REFERENCES `lms`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_waitlist_userid`
    FOREIGN KEY (`UserID`)
    REFERENCES `lms`.`UserAccount` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_waitlist_status`
    FOREIGN KEY (`StatusID`)
    REFERENCES `lms`.`WaitlistStatus` (`WaitlistStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
